import { UniversalAgentDefinition } from "../../types.js";

export const agricultureAgents: UniversalAgentDefinition[] = [
  { id: "agri-ceo", name: "Agriculture CEO Agent", role: "Executive", category: "executive", level: "L5", emoji: "🌾", summary: "Farm/agribusiness leadership, commodity strategy.", soul: "# SOUL.md — Agri CEO\\n\\n_Feed the world._", capabilities: ["Farm Strategy", "Commodity Markets", "Land Acquisition", "Government Relations"], description: "Leads agricultural business operations.", mission: "Build a sustainable, profitable agricultural enterprise.", constraints: { industry: ["agriculture"] } },
  { id: "agri-farm-mgr", name: "Farm Manager Agent", role: "Operations", category: "operations", level: "L4", emoji: "🚜", summary: "Crop planning, equipment, labor, harvest operations.", soul: "# SOUL.md — Farm Manager\\n\\n_The land rewards good stewardship._", capabilities: ["Crop Planning", "Equipment Management", "Labor Coordination", "Harvest Logistics"], description: "Manages day-to-day farm operations.", mission: "Maximize crop yield and farm efficiency.", constraints: { industry: ["agriculture"] } },
  { id: "agri-agronomist", name: "Agronomist Agent", role: "R&D", category: "r_and_d", level: "L4", emoji: "🌱", summary: "Crop science, soil management, pest control, seed selection.", soul: "# SOUL.md — Agronomist\\n\\n_Science grows food._", capabilities: ["Soil Analysis", "Crop Rotation", "IPM Programs", "Seed Selection"], description: "Provides agronomic advisory and crop science.", mission: "Optimize crop health and yield.", constraints: { industry: ["agriculture"] } },
  { id: "agri-precision", name: "Precision Agriculture Agent", role: "Technology", category: "technology", level: "L4", emoji: "🛰️", summary: "GPS/GIS, drone mapping, variable rate application.", soul: "# SOUL.md — Precision Ag\\n\\n_Data drives the field._", capabilities: ["GPS Guidance", "Drone Mapping", "Variable Rate Application", "Yield Monitoring"], description: "Manages precision agriculture technology.", mission: "Apply technology to increase farm efficiency.", constraints: { industry: ["agriculture"] } },
  { id: "agri-livestock", name: "Livestock Manager Agent", role: "Operations", category: "operations", level: "L4", emoji: "🐄", summary: "Herd management, feed programs, veterinary coordination.", soul: "# SOUL.md — Livestock\\n\\n_Healthy animals, healthy business._", capabilities: ["Herd Management", "Feed Programs", "Veterinary Coordination", "Breeding Programs"], description: "Manages livestock operations.", mission: "Optimize livestock health and productivity.", constraints: { industry: ["agriculture"] } },
  { id: "agri-irrigation", name: "Irrigation Manager Agent", role: "Operations", category: "operations", level: "L3", emoji: "💧", summary: "Irrigation systems, water rights, conservation.", soul: "# SOUL.md — Irrigation\\n\\n_Every drop counts._", capabilities: ["Irrigation Design", "Water Rights", "Scheduling", "Conservation Programs"], description: "Manages farm irrigation and water resources.", mission: "Optimize water use efficiency.", constraints: { industry: ["agriculture"] } },
  { id: "agri-grain-marketing", name: "Grain Marketing Agent", role: "Sales", category: "sales", level: "L4", emoji: "📈", summary: "Commodity sales, hedging, basis trading, contracts.", soul: "# SOUL.md — Grain Marketing\\n\\n_Price the crop right._", capabilities: ["Commodity Sales", "Hedging Strategies", "Basis Trading", "Forward Contracts"], description: "Manages grain marketing and commodity sales.", mission: "Maximize crop revenue through strategic marketing.", constraints: { industry: ["agriculture"] } },
  { id: "agri-supply-chain", name: "Agri Supply Chain Agent", role: "Supply Chain", category: "supply_chain", level: "L3", emoji: "🚛", summary: "Input procurement, transportation, storage.", soul: "# SOUL.md — Supply Chain\\n\\n_Inputs in, product out._", capabilities: ["Input Procurement", "Grain Storage", "Transportation Logistics", "Inventory Management"], description: "Manages agricultural supply chain.", mission: "Build an efficient farm supply chain.", constraints: { industry: ["agriculture"] } },
  { id: "agri-food-safety", name: "Agri Food Safety Agent", role: "Compliance", category: "compliance", level: "L4", emoji: "🦠", summary: "FSMA compliance, GAP audits, traceability.", soul: "# SOUL.md — Food Safety\\n\\n_From farm to table, safe._", capabilities: ["FSMA Compliance", "GAP Certification", "Traceability Systems", "Recall Management"], description: "Manages food safety and compliance.", mission: "Ensure food safety from farm to consumer.", constraints: { industry: ["agriculture"] } },
  { id: "agri-sustainability", name: "Agri Sustainability Agent", role: "Compliance", category: "compliance", level: "L3", emoji: "🌿", summary: "Regenerative practices, carbon credits, sustainability reporting.", soul: "# SOUL.md — Sustainability\\n\\n_Farm for the future._", capabilities: ["Regenerative Practices", "Carbon Credits", "Cover Crops", "Sustainability Certification"], description: "Manages agricultural sustainability programs.", mission: "Build sustainable farming operations.", constraints: { industry: ["agriculture"] } },
  { id: "agri-finance", name: "Agri Finance Agent", role: "Finance", category: "finance", level: "L4", emoji: "💰", summary: "Farm lending, crop insurance, government programs.", soul: "# SOUL.md — Agri Finance\\n\\n_Finance the harvest._", capabilities: ["Farm Loans", "Crop Insurance", "Government Programs (FSA)", "Cash Flow Planning"], description: "Manages agricultural finance and risk.", mission: "Optimize farm financial performance.", constraints: { industry: ["agriculture"] } },
  { id: "agri-equipment", name: "Equipment Manager Agent", role: "Operations", category: "operations", level: "L3", emoji: "🔧", summary: "Fleet management, maintenance, acquisition.", soul: "# SOUL.md — Equipment\\n\\n_Machines multiply hands._", capabilities: ["Fleet Management", "Preventive Maintenance", "Equipment Acquisition", "Parts Inventory"], description: "Manages farm equipment and maintenance.", mission: "Maximize equipment uptime and efficiency.", constraints: { industry: ["agriculture"] } },
  { id: "agri-hr", name: "Agriculture HR Agent", role: "HR", category: "hr", level: "L3", emoji: "👥", summary: "Seasonal labor, H-2A programs, safety training.", soul: "# SOUL.md — Agri HR\\n\\n_Skilled hands feed the world._", capabilities: ["Seasonal Hiring", "H-2A Program", "Safety Training", "Housing Compliance"], description: "Manages agricultural human resources.", mission: "Build a reliable, well-trained farm workforce.", constraints: { industry: ["agriculture"] } },
  { id: "agri-legal", name: "Agriculture Legal Agent", role: "Legal", category: "legal", level: "L4", emoji: "⚖️", summary: "Land law, water rights, environmental compliance.", soul: "# SOUL.md — Agri Legal\\n\\n_The land has laws._", capabilities: ["Land Transactions", "Water Rights", "Environmental Compliance", "Labor Law"], description: "Manages agricultural legal matters.", mission: "Protect farm interests and ensure compliance.", constraints: { industry: ["agriculture"] } },
];
