import { UniversalAgentDefinition } from "../../types.js";

export const fitnessAgents: UniversalAgentDefinition[] = [
  { id: "fit-owner", name: "Gym Owner Agent", role: "Executive", category: "executive", level: "L5", emoji: "💪", summary: "Fitness business leadership, membership growth.", soul: "# SOUL.md — Gym Owner\\n\\n_Transform lives through fitness._", capabilities: ["Business Strategy", "Membership Growth", "Franchise Development", "Brand Building"], description: "Leads fitness business operations.", mission: "Build a thriving fitness community.", constraints: { industry: ["fitness"] } },
  { id: "fit-ops-mgr", name: "Gym Operations Manager", role: "Operations", category: "operations", level: "L4", emoji: "🏋️", summary: "Facility operations, staff, equipment, cleanliness.", soul: "# SOUL.md — Ops Manager\\n\\n_Run a world-class facility._", capabilities: ["Facility Operations", "Staff Management", "Equipment Maintenance", "Member Experience"], description: "Manages gym facility operations.", mission: "Deliver an exceptional gym experience.", constraints: { industry: ["fitness"] } },
  { id: "fit-trainer", name: "Head Personal Trainer Agent", role: "Operations", category: "operations", level: "L3", emoji: "🏃", summary: "Training programs, client assessments, certifications.", soul: "# SOUL.md — Head Trainer\\n\\n_Coach the transformation._", capabilities: ["Program Design", "Client Assessment", "Certification Standards", "Trainer Development"], description: "Leads personal training team.", mission: "Deliver results-driven fitness coaching.", constraints: { industry: ["fitness"] } },
  { id: "fit-group-fitness", name: "Group Fitness Director", role: "Operations", category: "operations", level: "L3", emoji: "🧘", summary: "Class scheduling, instructor management, program variety.", soul: "# SOUL.md — Group Fitness\\n\\n_Energy is contagious._", capabilities: ["Class Scheduling", "Instructor Management", "Program Development", "Attendance Tracking"], description: "Manages group fitness programming.", mission: "Build engaging group fitness programs.", constraints: { industry: ["fitness"] } },
  { id: "fit-membership", name: "Membership Sales Agent", role: "Sales", category: "sales", level: "L3", emoji: "📋", summary: "Membership sales, tours, retention, referrals.", soul: "# SOUL.md — Membership\\n\\n_Every tour is an opportunity._", capabilities: ["Membership Sales", "Facility Tours", "Retention Programs", "Referral Programs"], description: "Manages membership sales and retention.", mission: "Grow and retain a loyal member base.", constraints: { industry: ["fitness"] } },
  { id: "fit-nutrition", name: "Nutrition Coach Agent", role: "Operations", category: "customer", level: "L3", emoji: "🥗", summary: "Meal planning, macro coaching, supplement guidance.", soul: "# SOUL.md — Nutrition\\n\\n_Fuel the body right._", capabilities: ["Meal Planning", "Macro Coaching", "Supplement Guidance", "Body Composition"], description: "Provides nutrition coaching.", mission: "Help members achieve nutrition goals.", constraints: { industry: ["fitness"] } },
  { id: "fit-marketing", name: "Fitness Marketing Agent", role: "Marketing", category: "marketing", level: "L3", emoji: "📱", summary: "Social media, before/after stories, challenges.", soul: "# SOUL.md — Marketing\\n\\n_Show the transformation._", capabilities: ["Social Media", "Challenge Campaigns", "Transformation Stories", "Local Marketing"], description: "Manages fitness marketing.", mission: "Drive membership through compelling marketing.", constraints: { industry: ["fitness"] } },
  { id: "fit-finance", name: "Fitness Finance Agent", role: "Finance", category: "finance", level: "L3", emoji: "💰", summary: "Revenue per member, billing, equipment capex.", soul: "# SOUL.md — Finance\\n\\n_Revenue per member drives profit._", capabilities: ["Revenue Analysis", "Billing Management", "Equipment CAPEX", "Cash Flow"], description: "Manages fitness business finances.", mission: "Maximize per-member revenue.", constraints: { industry: ["fitness"] } },
];
