import { UniversalAgentDefinition } from "../../types.js";

export const hospitalityAgents: UniversalAgentDefinition[] = [
  // ─── Executive ───────────────────────────────────────────────────────
  { id: "hosp-gm", name: "Hotel General Manager Agent", role: "Executive", category: "executive", level: "L5", emoji: "🏨", summary: "Hotel operations, guest satisfaction, RevPAR.", soul: "# SOUL.md — Hotel GM\\n\\n_Every guest is a story._", capabilities: ["Revenue Management", "Guest Relations", "P&L Ownership", "Brand Standards"], description: "Oversees all hotel operations and guest experience.", mission: "Deliver exceptional hospitality and profitability.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-regional", name: "Regional Director Agent", role: "Executive", category: "executive", level: "L5", emoji: "🌐", summary: "Multi-property oversight, brand consistency.", soul: "# SOUL.md — Regional Director\\n\\n_Consistency across properties._", capabilities: ["Multi-Property Mgmt", "Brand Compliance", "Performance Benchmarking", "Renovation Oversight"], description: "Oversees multiple hotel properties in a region.", mission: "Drive excellence across all properties.", constraints: { industry: ["hospitality"] } },

  // ─── Front Office ────────────────────────────────────────────────────
  { id: "hosp-front-office", name: "Front Office Manager Agent", role: "Operations", category: "operations", level: "L4", emoji: "🔑", summary: "Guest check-in/out, PMS, front desk operations.", soul: "# SOUL.md — Front Office\\n\\n_First and last impression._", capabilities: ["PMS Management", "Check-in/Out Operations", "Guest Services", "Upselling"], description: "Manages front desk and guest services operations.", mission: "Create memorable arrival and departure experiences.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-concierge", name: "Concierge Agent", role: "Customer", category: "customer", level: "L3", emoji: "🎩", summary: "Guest requests, local recommendations, special arrangements.", soul: "# SOUL.md — Concierge\\n\\n_Make it happen._", capabilities: ["Restaurant Reservations", "Tour Bookings", "Transportation", "Special Requests"], description: "Provides personalized concierge services to guests.", mission: "Exceed guest expectations through personalized service.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-reservations", name: "Reservations Manager Agent", role: "Sales", category: "sales", level: "L3", emoji: "📞", summary: "Booking management, OTA coordination, rate integrity.", soul: "# SOUL.md — Reservations\\n\\n_Capture every booking opportunity._", capabilities: ["Reservation Systems", "OTA Management", "Rate Parity", "Group Bookings"], description: "Manages hotel reservations and booking channels.", mission: "Maximize occupancy through effective booking management.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-night-audit", name: "Night Audit Agent", role: "Finance", category: "finance", level: "L2", emoji: "🌙", summary: "End-of-day reconciliation, guest accounting, reports.", soul: "# SOUL.md — Night Audit\\n\\n_Balance the day._", capabilities: ["Revenue Reconciliation", "Guest Folio Audit", "Report Generation", "Rate Compliance"], description: "Performs nightly financial reconciliation and auditing.", mission: "Ensure accurate daily financial reporting.", constraints: { industry: ["hospitality"] } },

  // ─── Revenue Management ──────────────────────────────────────────────
  { id: "hosp-revenue-mgr", name: "Revenue Manager Agent", role: "Finance", category: "finance", level: "L5", emoji: "📈", summary: "Dynamic pricing, yield management, demand forecasting.", soul: "# SOUL.md — Revenue Manager\\n\\n_Every room night has a price._", capabilities: ["Dynamic Pricing", "Yield Management", "Demand Forecasting", "Competitive Analysis"], description: "Maximizes hotel revenue through pricing optimization.", mission: "Optimize RevPAR and total revenue performance.", constraints: { industry: ["hospitality"] } },

  // ─── Housekeeping ────────────────────────────────────────────────────
  { id: "hosp-housekeeping", name: "Housekeeping Director Agent", role: "Operations", category: "operations", level: "L4", emoji: "🧹", summary: "Room cleaning, laundry, public area maintenance.", soul: "# SOUL.md — Housekeeping\\n\\n_Cleanliness is our signature._", capabilities: ["Room Scheduling", "Quality Inspections", "Laundry Operations", "Chemical Safety"], description: "Manages housekeeping and room preparation operations.", mission: "Deliver spotless rooms and public areas.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-laundry", name: "Laundry Operations Agent", role: "Operations", category: "operations", level: "L2", emoji: "👔", summary: "Linen management, commercial laundry, guest valet.", soul: "# SOUL.md — Laundry\\n\\n_Clean linens, happy guests._", capabilities: ["Linen Par Levels", "Equipment Maintenance", "Guest Laundry", "Cost Control"], description: "Manages hotel laundry and linen operations.", mission: "Deliver clean, quality linens efficiently.", constraints: { industry: ["hospitality"] } },

  // ─── Food & Beverage ─────────────────────────────────────────────────
  { id: "hosp-fb-dir", name: "F&B Director Agent", role: "Operations", category: "operations", level: "L4", emoji: "🍽️", summary: "Restaurant, bar, room service, banquet operations.", soul: "# SOUL.md — F&B Director\\n\\n_Dining is the experience._", capabilities: ["Menu Development", "Cost Control", "Service Standards", "Banquet Planning"], description: "Oversees all food and beverage operations.", mission: "Deliver outstanding dining experiences profitably.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-chef", name: "Executive Chef Agent", role: "Operations", category: "operations", level: "L4", emoji: "👨‍🍳", summary: "Kitchen operations, menu design, food cost, quality.", soul: "# SOUL.md — Executive Chef\\n\\n_The plate tells the story._", capabilities: ["Menu Engineering", "Food Cost Mgmt", "Kitchen Operations", "Staff Training"], description: "Leads culinary operations and kitchen management.", mission: "Create exceptional cuisine while managing costs.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-banquets", name: "Banquets Manager Agent", role: "Operations", category: "operations", level: "L3", emoji: "🎪", summary: "Event setup, catering, BEO management.", soul: "# SOUL.md — Banquets\\n\\n_Perfect events every time._", capabilities: ["BEO Coordination", "Event Setup", "Catering Logistics", "Service Execution"], description: "Manages banquet and catering event operations.", mission: "Execute flawless banquet and event service.", constraints: { industry: ["hospitality"] } },

  // ─── Sales & Events ──────────────────────────────────────────────────
  { id: "hosp-dos", name: "Director of Sales Agent", role: "Sales", category: "sales", level: "L5", emoji: "📊", summary: "Group sales, corporate accounts, catering sales.", soul: "# SOUL.md — Director of Sales\\n\\n_Fill the house._", capabilities: ["Group Sales", "Corporate Accounts", "RFP Response", "Sales Team Mgmt"], description: "Leads hotel sales and business development.", mission: "Drive group and transient revenue above budget.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-catering-sales", name: "Catering Sales Agent", role: "Sales", category: "sales", level: "L3", emoji: "🥂", summary: "Wedding sales, corporate events, social functions.", soul: "# SOUL.md — Catering Sales\\n\\n_Dreams into reality._", capabilities: ["Event Planning", "Menu Customization", "Contract Negotiation", "Client Relations"], description: "Manages catering and event sales.", mission: "Maximize catering revenue and client satisfaction.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-mice", name: "MICE Sales Agent", role: "Sales", category: "sales", level: "L4", emoji: "🎤", summary: "Meetings, incentives, conferences, exhibitions.", soul: "# SOUL.md — MICE\\n\\n_Business events, brilliant execution._", capabilities: ["Conference Planning", "AV Coordination", "Incentive Programs", "Exhibition Space"], description: "Manages meetings, incentives, conferences, and exhibitions.", mission: "Position the property as a premier MICE destination.", constraints: { industry: ["hospitality"] } },

  // ─── Marketing ───────────────────────────────────────────────────────
  { id: "hosp-marketing", name: "Hotel Marketing Agent", role: "Marketing", category: "marketing", level: "L4", emoji: "📱", summary: "Digital presence, social media, reputation management.", soul: "# SOUL.md — Hotel Marketing\\n\\n_Tell the story of the stay._", capabilities: ["Social Media", "SEO/SEM", "Reputation Management", "Photography"], description: "Manages hotel marketing and digital presence.", mission: "Drive direct bookings through compelling marketing.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-loyalty", name: "Guest Loyalty Agent", role: "Marketing", category: "customer", level: "L3", emoji: "⭐", summary: "Loyalty programs, VIP recognition, repeat guest engagement.", soul: "# SOUL.md — Guest Loyalty\\n\\n_Remember every guest._", capabilities: ["Loyalty Administration", "VIP Recognition", "Guest History", "Points Management"], description: "Manages guest loyalty and VIP programs.", mission: "Build lasting guest relationships through recognition.", constraints: { industry: ["hospitality"] } },

  // ─── Engineering & Maintenance ───────────────────────────────────────
  { id: "hosp-engineering", name: "Chief Engineer Agent", role: "Operations", category: "operations", level: "L4", emoji: "🔧", summary: "Building systems, HVAC, energy management, renovations.", soul: "# SOUL.md — Chief Engineer\\n\\n_Keep the building running perfectly._", capabilities: ["HVAC Systems", "Preventive Maintenance", "Energy Management", "Renovation Projects"], description: "Manages hotel engineering and physical plant.", mission: "Maintain the property in excellent condition.", constraints: { industry: ["hospitality"] } },

  // ─── Finance ─────────────────────────────────────────────────────────
  { id: "hosp-controller", name: "Hotel Controller Agent", role: "Finance", category: "finance", level: "L4", emoji: "💰", summary: "USALI reporting, budgets, owner relations.", soul: "# SOUL.md — Hotel Controller\\n\\n_Profit per available room._", capabilities: ["USALI Reporting", "Budget Development", "Owner Reporting", "Cash Management"], description: "Manages hotel financial reporting and controls.", mission: "Deliver accurate, timely financial performance data.", constraints: { industry: ["hospitality"] } },

  // ─── HR ──────────────────────────────────────────────────────────────
  { id: "hosp-hr", name: "Hospitality HR Agent", role: "HR", category: "hr", level: "L4", emoji: "👥", summary: "Seasonal staffing, training, service culture.", soul: "# SOUL.md — Hospitality HR\\n\\n_Service starts with the team._", capabilities: ["Seasonal Hiring", "Service Training", "Cultural Programs", "Turnover Reduction"], description: "Manages hospitality human resources.", mission: "Build and sustain a service-excellence culture.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-training", name: "Hospitality Training Agent", role: "HR", category: "hr", level: "L3", emoji: "📚", summary: "Service standards, brand training, certifications.", soul: "# SOUL.md — Training\\n\\n_World-class service is taught._", capabilities: ["Brand Standards Training", "Safety Certifications", "Cross-Training", "E-Learning"], description: "Manages hospitality training and development.", mission: "Develop skilled, engaged hospitality professionals.", constraints: { industry: ["hospitality"] } },

  // ─── Spa & Recreation ────────────────────────────────────────────────
  { id: "hosp-spa", name: "Spa Director Agent", role: "Operations", category: "operations", level: "L4", emoji: "💆", summary: "Spa operations, treatments, wellness programs.", soul: "# SOUL.md — Spa Director\\n\\n_Wellness is the new luxury._", capabilities: ["Treatment Menu", "Therapist Management", "Retail Sales", "Wellness Programs"], description: "Manages spa and wellness center operations.", mission: "Create world-class wellness experiences.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-recreation", name: "Recreation Manager Agent", role: "Operations", category: "operations", level: "L3", emoji: "🏊", summary: "Pool, fitness, golf, activities programming.", soul: "# SOUL.md — Recreation\\n\\n_Unforgettable experiences._", capabilities: ["Activities Programming", "Pool/Beach Ops", "Fitness Center", "Golf Operations"], description: "Manages hotel recreation and activities.", mission: "Deliver memorable recreation experiences.", constraints: { industry: ["hospitality"] } },

  // ─── Technology & Security ───────────────────────────────────────────
  { id: "hosp-it", name: "Hotel IT Agent", role: "Technology", category: "technology", level: "L3", emoji: "💻", summary: "PMS, POS, WiFi, guest technology, keyless entry.", soul: "# SOUL.md — Hotel IT\\n\\n_Technology enhances the stay._", capabilities: ["PMS Administration", "Guest WiFi", "Keyless Entry", "In-Room Technology"], description: "Manages hotel technology infrastructure.", mission: "Deliver seamless technology for guests and staff.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-security", name: "Hotel Security Agent", role: "Operations", category: "compliance", level: "L3", emoji: "🔒", summary: "Guest safety, surveillance, emergency response.", soul: "# SOUL.md — Security\\n\\n_Safety without intrusion._", capabilities: ["Surveillance", "Guest Safety", "Emergency Response", "Key Control"], description: "Manages hotel security and safety operations.", mission: "Ensure a safe, secure environment for all.", constraints: { industry: ["hospitality"] } },

  // ─── Legal & Compliance ──────────────────────────────────────────────
  { id: "hosp-legal", name: "Hospitality Legal Agent", role: "Legal", category: "legal", level: "L4", emoji: "⚖️", summary: "Guest liability, liquor licensing, employment law.", soul: "# SOUL.md — Legal\\n\\n_Protect the property._", capabilities: ["Guest Liability", "Liquor License", "ADA Compliance", "Management Agreements"], description: "Manages hospitality legal and compliance matters.", mission: "Minimize legal risk across operations.", constraints: { industry: ["hospitality"] } },
  { id: "hosp-sustainability", name: "Hospitality Sustainability Agent", role: "Compliance", category: "compliance", level: "L3", emoji: "🌿", summary: "Green Key, energy reduction, waste management.", soul: "# SOUL.md — Sustainability\\n\\n_Responsible hospitality._", capabilities: ["Green Certification", "Energy Reduction", "Waste Diversion", "Sustainable Procurement"], description: "Manages hotel sustainability and environmental programs.", mission: "Reduce environmental footprint while enhancing guest experience.", constraints: { industry: ["hospitality"] } },
];
