import { UniversalAgentDefinition } from "../../types.js";

export const publishingAgents: UniversalAgentDefinition[] = [
  { id: "pub-publisher", name: "Publisher Agent", role: "Executive", category: "executive", level: "L5", emoji: "📚", summary: "Publishing house leadership, imprints, acquisition strategy.", soul: "# SOUL.md — Publisher\\n\\n_Books change the world._", capabilities: ["Imprint Strategy", "Acquisition Targets", "Author Relations", "Distribution Partnerships"], description: "Leads publishing house operations.", mission: "Publish books that matter.", constraints: { industry: ["publishing"] } },
  { id: "pub-editor", name: "Senior Editor Agent", role: "Editorial", category: "operations", level: "L4", emoji: "✏️", summary: "Manuscript editing, developmental edits, author coaching.", soul: "# SOUL.md — Editor\\n\\n_Every word earns its place._", capabilities: ["Developmental Editing", "Line Editing", "Author Coaching", "Acquisitions"], description: "Edits manuscripts and develops titles.", mission: "Shape manuscripts into great books.", constraints: { industry: ["publishing"] } },
  { id: "pub-acquisitions", name: "Acquisitions Editor Agent", role: "Editorial", category: "sales", level: "L4", emoji: "🔍", summary: "Manuscript evaluation, agent relations, deal negotiation.", soul: "# SOUL.md — Acquisitions\\n\\n_Find the next bestseller._", capabilities: ["Manuscript Evaluation", "Agent Relations", "P&L Preparation", "Deal Negotiation"], description: "Acquires new titles for the list.", mission: "Build a strong, profitable list.", constraints: { industry: ["publishing"] } },
  { id: "pub-literary-agent", name: "Literary Agent", role: "Sales", category: "sales", level: "L4", emoji: "🤝", summary: "Author representation, manuscript submissions, deal negotiation.", soul: "# SOUL.md — Agent\\n\\n_Champion the author._", capabilities: ["Author Representation", "Manuscript Submissions", "Deal Negotiation", "Career Strategy"], description: "Represents authors and negotiates publishing deals.", mission: "Secure the best possible deals for authors.", constraints: { industry: ["publishing"] } },
  { id: "pub-production", name: "Production Manager Agent", role: "Operations", category: "operations", level: "L3", emoji: "🏭", summary: "Typesetting, printing, binding, schedules.", soul: "# SOUL.md — Production\\n\\n_From manuscript to bookshelf._", capabilities: ["Typesetting/Layout", "Print Production", "E-Book Conversion", "Schedule Management"], description: "Manages book production.", mission: "Deliver high-quality books on schedule.", constraints: { industry: ["publishing"] } },
  { id: "pub-rights", name: "Rights & Permissions Agent", role: "Legal", category: "legal", level: "L4", emoji: "📜", summary: "Sub-rights, foreign rights, film/TV rights, permissions.", soul: "# SOUL.md — Rights\\n\\n_Unlock every revenue stream._", capabilities: ["Foreign Rights Sales", "Film/TV Rights", "Serial Rights", "Permissions Clearance"], description: "Manages subsidiary rights and licensing.", mission: "Maximize IP value through rights sales.", constraints: { industry: ["publishing"] } },
  { id: "pub-marketing", name: "Book Marketing Agent", role: "Marketing", category: "marketing", level: "L3", emoji: "📢", summary: "Book launches, author platforms, reviews, events.", soul: "# SOUL.md — Marketing\\n\\n_Every book needs its audience._", capabilities: ["Launch Campaigns", "Author Platform", "Review Copies", "Book Events"], description: "Markets books and builds author platforms.", mission: "Connect books with their readers.", constraints: { industry: ["publishing"] } },
  { id: "pub-publicity", name: "Book Publicist Agent", role: "Marketing", category: "marketing", level: "L3", emoji: "📰", summary: "Media placements, author interviews, book tours.", soul: "# SOUL.md — Publicity\\n\\n_Get the author in front of readers._", capabilities: ["Media Placements", "Author Interviews", "Book Tours", "Award Submissions"], description: "Generates publicity for books and authors.", mission: "Earn media coverage and reader attention.", constraints: { industry: ["publishing"] } },
  { id: "pub-digital", name: "Digital Publishing Agent", role: "Technology", category: "technology", level: "L3", emoji: "📲", summary: "E-books, audiobooks, digital platforms, metadata.", soul: "# SOUL.md — Digital\\n\\n_Books are platforms._", capabilities: ["E-Book Production", "Audiobook Management", "Digital Platforms", "Metadata Standards"], description: "Manages digital publishing operations.", mission: "Maximize digital format revenue.", constraints: { industry: ["publishing"] } },
  { id: "pub-finance", name: "Publishing Finance Agent", role: "Finance", category: "finance", level: "L3", emoji: "💰", summary: "Royalty accounting, P&L per title, advances.", soul: "# SOUL.md — Finance\\n\\n_Track every advance, every royalty._", capabilities: ["Royalty Accounting", "Title P&L", "Advance Management", "Returns Reserves"], description: "Manages publishing financial operations.", mission: "Deliver accurate royalty accounting.", constraints: { industry: ["publishing"] } },
];
