import { UniversalAgentDefinition } from "../types.js";

export const wasteManagementAgents: UniversalAgentDefinition[] = [
  { id: "waste-ceo", name: "Waste Management CEO", role: "Executive", category: "executive", level: "L5", emoji: "♻️", summary: "Waste company leadership, franchise areas, fleet.", soul: "# SOUL.md — CEO\\n\\n_Manage waste, manage health._", capabilities: ["Franchise Strategy", "Municipal Contracts", "Fleet Investment", "Recycling Programs"], description: "Leads waste management company.", mission: "Build essential waste management infrastructure.", constraints: { industry: ["waste_management"] } },
  { id: "waste-collection", name: "Collection Operations Agent", role: "Operations", category: "operations", level: "L4", emoji: "🚛", summary: "Route planning, truck dispatch, service schedules.", soul: "# SOUL.md — Collection\\n\\n_Every curb, every day._", capabilities: ["Route Optimization", "Truck Dispatch", "Service Schedules", "Container Management"], description: "Manages waste collection operations.", mission: "Deliver reliable, efficient collection service.", constraints: { industry: ["waste_management"] } },
  { id: "waste-mrf", name: "MRF Manager Agent", role: "Operations", category: "operations", level: "L4", emoji: "🏭", summary: "Materials recovery facility, sorting, baling, commodity sales.", soul: "# SOUL.md — MRF\\n\\n_One person's trash is another's resource._", capabilities: ["Sorting Operations", "Contamination Control", "Commodity Sales", "Equipment Maintenance"], description: "Manages materials recovery facility.", mission: "Maximize recycling recovery rates.", constraints: { industry: ["waste_management"] } },
  { id: "waste-landfill", name: "Landfill Manager Agent", role: "Operations", category: "operations", level: "L4", emoji: "🏔️", summary: "Landfill operations, cell design, gas collection, closure.", soul: "# SOUL.md — Landfill\\n\\n_Engineered containment._", capabilities: ["Cell Design", "Leachate Management", "Gas Collection", "Closure Plans"], description: "Manages landfill operations.", mission: "Operate a safe, compliant landfill.", constraints: { industry: ["waste_management"] } },
  { id: "waste-hazmat", name: "Hazmat Operations Agent", role: "Operations", category: "compliance", level: "L4", emoji: "☢️", summary: "Hazardous waste handling, manifesting, disposal.", soul: "# SOUL.md — Hazmat\\n\\n_Handle with extreme care._", capabilities: ["Hazmat Handling", "Waste Manifesting", "DOT Compliance", "RCRA Disposal"], description: "Manages hazardous waste operations.", mission: "Ensure safe, compliant hazardous waste management.", constraints: { industry: ["waste_management"] } },
  { id: "waste-compliance", name: "Waste Compliance Agent", role: "Compliance", category: "compliance", level: "L4", emoji: "📋", summary: "EPA/state permits, reporting, inspections.", soul: "# SOUL.md — Compliance\\n\\n_Permit compliance protects everyone._", capabilities: ["EPA Compliance", "State Permits", "Reporting", "Inspection Prep"], description: "Manages waste regulatory compliance.", mission: "Maintain full environmental compliance.", constraints: { industry: ["waste_management"] } },
  { id: "waste-sales", name: "Waste Services Sales Agent", role: "Sales", category: "sales", level: "L3", emoji: "🤝", summary: "Commercial/municipal contracts, service proposals.", soul: "# SOUL.md — Sales\\n\\n_Essential service, competitive market._", capabilities: ["Commercial Sales", "Municipal RFPs", "Service Proposals", "Contract Negotiation"], description: "Drives waste services sales.", mission: "Win and grow service contracts.", constraints: { industry: ["waste_management"] } },
  { id: "waste-finance", name: "Waste Finance Agent", role: "Finance", category: "finance", level: "L3", emoji: "💰", summary: "Route profitability, disposal costs, tipping fees.", soul: "# SOUL.md — Finance\\n\\n_Revenue per route, cost per ton._", capabilities: ["Route Profitability", "Disposal Cost Analysis", "Tipping Fee Management", "Fleet CAPEX"], description: "Manages waste company finances.", mission: "Optimize route and disposal economics.", constraints: { industry: ["waste_management"] } },
];
